---
# defaults file for hswong3i.confluence

# required variables
confluence_gid: ~
confluence_hash_salt: ~
confluence_pass: ~
confluence_uid: ~
confluence_user: ~

# optional variables with default
confluence_archive: "atlassian-confluence-5.10.3.tar.gz"
confluence_catalina: "/usr/share/confluence"
confluence_checksum: "sha256:6e48857c85cdc011e75d52e4d23fa32e9c053051f132d642b284e050fd5735ab"
confluence_connector_port: "8090"
confluence_context_path: ~
confluence_home: "/var/lib/confluence"
confluence_jvm_maximum_memory: "1024m"
confluence_jvm_minimum_memory: "512m"
confluence_jvm_support_recommended_args: "-Datlassian.plugins.enable.wait=300"
confluence_proxy_name: ~
confluence_scheme: ~
confluence_server_port: "8000"
confluence_url: "https://downloads.atlassian.com/software/confluence/downloads/{{ confluence_archive }}"
