---
# defaults file for hswong3i.bamboo

# required variables
bamboo_gid: ~
bamboo_hash_salt: ~
bamboo_pass: ~
bamboo_uid: ~
bamboo_user: ~

# optional variables with default
bamboo_archive: "atlassian-bamboo-5.12.3.1.tar.gz"
bamboo_catalina: "/usr/share/bamboo"
bamboo_checksum: "sha256:012d40a06aeda188ccd9d84d5b520d51e92dfd5ef081d1a8a8e9a9f333e01a5b"
bamboo_connector_port: "8085"
bamboo_context_path: ~
bamboo_home: "/var/lib/bamboo"
bamboo_jvm_maximum_memory: "1024m"
bamboo_jvm_minimum_memory: "512m"
bamboo_jvm_support_recommended_args: "-Datlassian.plugins.enable.wait=300"
bamboo_proxy_name: ~
bamboo_scheme: ~
bamboo_server_port: "8007"
bamboo_url: "https://downloads.atlassian.com/software/bamboo/downloads/{{ bamboo_archive }}"
