---

galaxy_info:
  author: Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
  description: Ansible Role for Atlassian JIRA Installation.
  company: PantaRei Design
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
  galaxy_tags:
    - system
dependencies: []
