---
# Update playbook, Run with --check -v first to determine packages being upgraded
- hosts: all
  become: true

  tasks:

    - name: Get aptitude for upgrade
      apt: pkg=aptitude state=present

    - name: Update Debian based distros
      apt: update_cache=yes
           cache_valid_time=600
           upgrade=yes
      when: ansible_os_family == 'Debian'

    - name: Update RedHat based distros
      yum: name=*
           state=latest
      when: ansible_os_family == 'RedHat'
